apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: trudesk
  name: trudesk
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: trudesk
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: trudesk
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: production
            - name: TD_MONGODB_DATABASE
              value: trudesk
            - name: TD_MONGODB_SERVER
              value: mongo
            - name: TRUDESK_DOCKER
              value: 'true'
          image: polonel/trudesk:1
          name: trudesk
          ports:
            - containerPort: 8118

          readinessProbe:
            tcpSocket:
              port: 8118
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 8118
            initialDelaySeconds: 15
            periodSeconds: 20

          resources: {}
          volumeMounts:
            - mountPath: /usr/src/trudesk/public/uploads
              name: trudesk-uploads
            - mountPath: /usr/src/trudesk/backups
              name: trudesk-backups
            - mountPath: /usr/src/trudesk/config.yml
              name: trudesk-config-yml
              readOnly: true
              subPath: config.yml
      restartPolicy: Always
      volumes:
        - name: trudesk-uploads
          persistentVolumeClaim:
            claimName: trudesk-uploads
        - name: trudesk-backups
          persistentVolumeClaim:
            claimName: trudesk-backups
        - name: trudesk-config-yml
          configMap:
            name: trudesk-config-yml
status: {}


